### ISSUE TITLE
Not compatible with Python 3.9 pip3

### ISSUE THREAD

**Issue by dstrohmaier** [decompositional-semantics-initiative/decomp#26]
The version of setuptools required in requirements.txt is not compatible with pip3 that comes with Python 3.9. The general issue is discussed here:
https://stackoverflow.com/questions/65640476/pip3-on-python3-9-fails-on-htmlparser-object-has-no-attribute-unescape

It might be worth seeing whether the setuptools version can be pushed up and enable using Python 3.9. In any case, it would be useful to mention the required Python version in the readme.

**Comment by wgantt** [comment]
Thanks for bringing this to our attention! I'll investigate soon.

**Comment by wgantt** [comment]
@dstrohmaier: I believe I've resolved this by bumping the `setuptools` version (see [here](https://github.com/decompositional-semantics-initiative/decomp/commit/c3c2e8cae8c4e46382fd1d08aae700e529ea4cee)). Fixing this unmasked a compatibility issue between NetworkX and Python 3.9, which I also fixed. I'm closing this out, but do reopen it if the issue persists.
